apiVersion: v1
baseDomain: test.local
metadata:
  name: sno

networking:
  networkType: OVNKubernetes
  machineCIDR: 10.66.0.0/24
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16

platform:
  none: {}

controlPlane:
  name: master
  replicas: 1
  architecture: amd64
  platform: {}

compute:
  - name: worker
    replicas: 0
    architecture: amd64
    platform: {}

sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdfUJjRAJuFcdO0J8CIOkjaKpqP6h9TqDRhZOJTac0199gFUvAJF9R/MAqwDLi2QI6OtYjz1CiCSVLtVQ2fTTIdwVibr+ZKDcbx/E7ivKUUbcmAOU8NP1gv3e3anoUd5k/0h0krP88CXosr41eTih4EcKhBAKbeZ11M0i9GZOux+/WweLtSQ3NU07sUkf1jDIoBungg77unmadqP3m9PUdkFP7tZ2lufcs3iq+vq8JaUBs/hZKNmWOXpnAyNxD9RlBJmvW2QgHmX53y3WC9bWUEUrwfDMB2wAqWPEDfj+5jsXQZcVE4pqD6T1cPaITnr9KFGnCCG1VQg31t1Jttg8z vhgalvez@gmail.com

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTk5M2RiN2MwMDNkNDFlNDhmZGU4ZGE0OWIxZmZkYTI6WkhMMk5HUVFTS01aS1JJSTBPME5aUzFaSVgwQU9GTTNDQjdQUkxMMjc5UzRZN1BKSTBURVdSQUhLSFFZVVJOUw==","email":"vhgalvez@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTk5M2RiN2MwMDNkNDFlNDhmZGU4ZGE0OWIxZmZkYTI6WkhMMk5HUVFTS01aS1JJSTBPME5aUzFaSVgwQU9GTTNDQjdQUkxMMjc5UzRZN1BKSTBURVdSQUhLSFFZVVJOUw==","email":"vhgalvez@gmail.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWM1NzlhOGQ5LTA3YmItNDBmNy05OTgxLWNlODRlZmZhZDI2YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBPRGMxWVRVd01qSmlObU0wWW1KallqRXdNV0V3T1RjM01UQXhNR0k1WWlKOS5ZY0NRSl9XeldjLUFxNVc0UzlGNHE3ajNzbk9DelRmb3V0THRLS05EXzRWMGc2UWdGejZwdWh6N1pVcmEzUzFsUkptUXRWWUJETzFSRWtpT2tCYkR6UEVqVC1PSG1mSDhHcDRnTlN3TG5JZTRzeWdWMUMxWXBIU1NnUldncWlaaFBzMVlQTGJXazh6M0tfOEpNZlhtbUsyVS14dHVYeFVpbnMtLVo3NHd4MDdVWExtd2UwVk9DN0ROWDAwM0FGLUxhbFY5bnY4eVVMWnYzSlJnR0VjOFhuRkZxOWNrNWpCV2ZkVHhJd1VOdFBHYXpBcGhRZ0t1clloLWRmYVpLZkowaVRJVkV5RjBjR09DWWtPRlE0U2pJRE85b2xtZmhjektEblIyOEJSd2QtUE5JcEFzSk9teWRZRjVHdGdTNWtjZE9mV2dldUxxYjluUW1yMFExbXpzdmhhbnNsandxNFdtRUhaWFJ1dVo0NkU5cWVWMXgzZU51QzQyclF5d3dBUnRsdVJwNXpPam9SN3ViZHFHTldqLTIyWTZybi16aVZfbXRBV1R0eENsZjNPVTlqNWJDLU0yNTdIdWg3WGt1cFJ4bWZYcHVsSmpnZGlmQlIyaGNHMVNQVjBxT2pBZjA3NVRGZU5Yc2pOTlZnQWhFb2VmLTEtMHc4WGhISVdaZVBXT1lyRG9mR3dfcE1kclZqWWVUd19xSGpfQzAwa2lISmhOMkFQXzJRQnQzMHNhdVFuYk01c3g2WGpZUjBqNENDRTJaSDNJdkNOYWFNUHdreGJ4a0FaN3ZvbjhyWTNrZjAwa3RacFhmTjJPWDR4bHNFWmljZ0x6NFJjV2RHNFlVNG42cDJleVRPMWJCOEpYRmRpTjNZQmNhYkI3OFpnU1Y5bHlZWW52dTRacmtZRQ==","email":"vhgalvez@gmail.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWM1NzlhOGQ5LTA3YmItNDBmNy05OTgxLWNlODRlZmZhZDI2YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBPRGMxWVRVd01qSmlObU0wWW1KallqRXdNV0V3T1RjM01UQXhNR0k1WWlKOS5ZY0NRSl9XeldjLUFxNVc0UzlGNHE3ajNzbk9DelRmb3V0THRLS05EXzRWMGc2UWdGejZwdWh6N1pVcmEzUzFsUkptUXRWWUJETzFSRWtpT2tCYkR6UEVqVC1PSG1mSDhHcDRnTlN3TG5JZTRzeWdWMUMxWXBIU1NnUldncWlaaFBzMVlQTGJXazh6M0tfOEpNZlhtbUsyVS14dHVYeFVpbnMtLVo3NHd4MDdVWExtd2UwVk9DN0ROWDAwM0FGLUxhbFY5bnY4eVVMWnYzSlJnR0VjOFhuRkZxOWNrNWpCV2ZkVHhJd1VOdFBHYXpBcGhRZ0t1clloLWRmYVpLZkowaVRJVkV5RjBjR09DWWtPRlE0U2pJRE85b2xtZmhjektEblIyOEJSd2QtUE5JcEFzSk9teWRZRjVHdGdTNWtjZE9mV2dldUxxYjluUW1yMFExbXpzdmhhbnNsandxNFdtRUhaWFJ1dVo0NkU5cWVWMXgzZU51QzQyclF5d3dBUnRsdVJwNXpPam9SN3ViZHFHTldqLTIyWTZybi16aVZfbXRBV1R0eENsZjNPVTlqNWJDLU0yNTdIdWg3WGt1cFJ4bWZYcHVsSmpnZGlmQlIyaGNHMVNQVjBxT2pBZjA3NVRGZU5Yc2pOTlZnQWhFb2VmLTEtMHc4WGhISVdaZVBXT1lyRG9mR3dfcE1kclZqWWVUd19xSGpfQzAwa2lISmhOMkFQXzJRQnQzMHNhdVFuYk01c3g2WGpZUjBqNENDRTJaSDNJdkNOYWFNUHdreGJ4a0FaN3ZvbjhyWTNrZjAwa3RacFhmTjJPWDR4bHNFWmljZ0x6NFJjV2RHNFlVNG42cDJleVRPMWJCOEpYRmRpTjNZQmNhYkI3OFpnU1Y5bHlZWW52dTRacmtZRQ==","email":"vhgalvez@gmail.com"}}}'